# -*- coding: utf-8 -*-
"""Untitled0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ZSYYtPRq3c-0RHtoKfQdo_Q6fk6BofS
"""

# importing libraries
import datetime
import pandas as pd
import smtplib
import ssl
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM


# load birthday datalist
df = pd.read_csv(r"./final.csv")
df

# function that send emails


def email_func(subject, birthday_receiver, name):
    # store emails and password for receiver and sender
    receiver = birthday_receiver
    sender = 'dbitdocs@gmail.com'
    sender_password = 'Skyisblue2.'

    # create a MIMEMultipart object
    msg = MM()
    msg['Subject'] = subject + '' + str(name)+'!'

    # create html for the message
    HTML = """
  <html>
    <body>
      <h1>happy birthday</h1>
      <img src="https://www.flickr.com/photos/stunnglukz/39482401555/" width="640" height="360"></img>      
      <h2>
      <p> hello,<br>
      I hope you have a wonderful day today!<br><br>
      From;<br>
      Bhoom
      <p>
      </h2>
    </body>
  </html>
  """


# create a html MIMEText object
    MTObj = MT(HTML, "html")


# attach the mimetext object into msg container
    msg.attach(MTObj)

    SSL_context = ssl.create_default_context()
    server = smtplib.SMTP_SSL(host="smtp.gmail.com",
                              port=465, context=SSL_context)

    server.login(sender, sender_password)

    server.sendmail(sender, receiver, msg.as_string())


# getdate
today = datetime.date.today()
# getyear
year = today.year
# looping
for i in range(0, len(df)):
    month = df['Birth_Month'][i]
    day = df['Birth_Day'][i]
    name = df['Name'][i]
    email = df['Email'][i]
    birthdate = datetime.date(year, month, day)

    if birthdate == today:
        email_func('Happy birthday', email, name)
        print('sent successfully')
    else:
        print('its nt their bday today')
